[bundles]
junit-testing = ["assertj-core", "junit-jupiter-api", "junit-jupiter-params"]

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.23.1" }
junit-bom = { module = "org.junit:junit-bom", version = "5.9.1" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }

[plugins]
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.6" }
