name: CI

on:
  push:
    branches:
      - main

jobs:
  java:
    name: Exercise Java version
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        include:
          - java-version: 11
          - java-version: 17
          - java-version: 18

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --info

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: test-results-native
          path: |
            **/build/reports/*
            **/build/test-results/*
